//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMerge.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMerge.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Diff 的本地化字符串。
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return ResourceManager.GetString("Button_ExtractDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Log 的本地化字符串。
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildCellBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Column Base Log 的本地化字符串。
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildColumnBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Row Base Log 的本地化字符串。
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildRowBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy as CSV 的本地化字符串。
        /// </summary>
        public static string ContextMenu_CopyAsCsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy as TSV 的本地化字符串。
        /// </summary>
        public static string ContextMenu_CopyAsTsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsTsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract diff with this row as column header. 的本地化字符串。
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return ResourceManager.GetString("ContextMenu_DiffAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑Reset Column Header 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ←Reset Row Header 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑Set Column Header 的本地化字符串。
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ←Set Row Header 的本地化字符串。
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ${LEFT} → ${RIGHT} 的本地化字符串。
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot; 的本地化字符串。
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return ResourceManager.GetString("DefaultLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;${ROW}&quot; was added. 的本地化字符串。
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatAddedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;${ROW}&quot; was removed. 的本地化字符串。
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatRemovedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ${LEFT} → ${RIGHT} 的本地化字符串。
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultRowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        public static string GroupBox_Behavior {
            get {
                return ResourceManager.GetString("GroupBox_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Format 的本地化字符串。
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return ResourceManager.GetString("GroupBox_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Format 的本地化字符串。
        /// </summary>
        public static string GroupBox_LogFormat {
            get {
                return ResourceManager.GetString("GroupBox_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Setting 的本地化字符串。
        /// </summary>
        public static string GroupBox_ReadSetting {
            get {
                return ResourceManager.GetString("GroupBox_ReadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        public static string GroupBox_Style {
            get {
                return ResourceManager.GetString("GroupBox_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added Color 的本地化字符串。
        /// </summary>
        public static string Label_AddedColor {
            get {
                return ResourceManager.GetString("Label_AddedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added Row Log Format 的本地化字符串。
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_AddedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added Rows({0}) 的本地化字符串。
        /// </summary>
        public static string Label_AddedRows {
            get {
                return ResourceManager.GetString("Label_AddedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always expand cell diff 的本地化字符串。
        /// </summary>
        public static string Label_AlwaysExpandCellDiff {
            get {
                return ResourceManager.GetString("Label_AlwaysExpandCellDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Modified Row 的本地化字符串。
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return ResourceManager.GetString("Label_ColorModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Base Log Format 的本地化字符串。
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_ColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Header Color 的本地化字符串。
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return ResourceManager.GetString("Label_ColumnHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Width 的本地化字符串。
        /// </summary>
        public static string Label_ColumnWidth {
            get {
                return ResourceManager.GetString("Label_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit Cell Height 的本地化字符串。
        /// </summary>
        public static string Label_FitRowHeight {
            get {
                return ResourceManager.GetString("Label_FitRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus first diff when extracted 的本地化字符串。
        /// </summary>
        public static string Label_FocusFirstDiff {
            get {
                return ResourceManager.GetString("Label_FocusFirstDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore File Setting 的本地化字符串。
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return ResourceManager.GetString("Label_IgnoreFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Cell Log Format 的本地化字符串。
        /// </summary>
        public static string Label_LogFormat {
            get {
                return ResourceManager.GetString("Label_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Row Height 的本地化字符串。
        /// </summary>
        public static string Label_MaxRowHeight {
            get {
                return ResourceManager.GetString("Label_MaxRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Row Height 的本地化字符串。
        /// </summary>
        public static string Label_MinRowHeight {
            get {
                return ResourceManager.GetString("Label_MinRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Cells({0}) 的本地化字符串。
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return ResourceManager.GetString("Label_ModifiedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Color 的本地化字符串。
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return ResourceManager.GetString("Label_ModifiedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Row Color 的本地化字符串。
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return ResourceManager.GetString("Label_ModifiedRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Rows({0}) 的本地化字符串。
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return ResourceManager.GetString("Label_ModifiedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show dialog if no diff 的本地化字符串。
        /// </summary>
        public static string Label_NotifyEqual {
            get {
                return ResourceManager.GetString("Label_NotifyEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed Color 的本地化字符串。
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return ResourceManager.GetString("Label_RemovedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed Row Log Format 的本地化字符串。
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_RemovedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed Rows({0}) 的本地化字符串。
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return ResourceManager.GetString("Label_RemovedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Base Log Format 的本地化字符串。
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_RowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Colors 的本地化字符串。
        /// </summary>
        public static string Label_RowColor {
            get {
                return ResourceManager.GetString("Label_RowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Header Color 的本地化字符串。
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return ResourceManager.GetString("Label_RowHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Height 的本地化字符串。
        /// </summary>
        public static string Label_RowlHeight {
            get {
                return ResourceManager.GetString("Label_RowlHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip first blank columns 的本地化字符串。
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip first blank rows 的本地化字符串。
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trim last blank columns 的本地化字符串。
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trim last blank rows 的本地化字符串。
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console 的本地化字符串。
        /// </summary>
        public static string MenuItem_Console {
            get {
                return ResourceManager.GetString("MenuItem_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute external command 的本地化字符串。
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return ResourceManager.GetString("MenuItem_ExeExternalCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Commands 的本地化字符串。
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return ResourceManager.GetString("MenuItem_ExternalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Settings 的本地化字符串。
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return ResourceManager.GetString("MenuItem_FileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Setting 的本地化字符串。
        /// </summary>
        public static string MenuItem_GeneralSetting {
            get {
                return ResourceManager.GetString("MenuItem_GeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open as Dst File 的本地化字符串。
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open as Src File 的本地化字符串。
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open dst File 的本地化字符串。
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open src file 的本地化字符串。
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Files 的本地化字符串。
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent File Sets 的本地化字符串。
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return ResourceManager.GetString("MenuItem_RecentFileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no difference. 的本地化字符串。
        /// </summary>
        public static string Message_NoDiff {
            get {
                return ResourceManager.GetString("Message_NoDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please restart to apply the changes. 的本地化字符串。
        /// </summary>
        public static string Message_Reboot {
            get {
                return ResourceManager.GetString("Message_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting Diff ... 的本地化字符串。
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return ResourceManager.GetString("Msg_ExtractingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;. 的本地化字符串。
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return ResourceManager.GetString("Msg_OutofSheetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Files ... 的本地化字符串。
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return ResourceManager.GetString("Msg_ReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not be displayed 的本地化字符串。
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return ResourceManager.GetString("Msg_Undisplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are too many records. Display only around diff. 的本地化字符串。
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return ResourceManager.GetString("Msg_WarnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return ResourceManager.GetString("RadioButton_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Diff 的本地化字符串。
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return ResourceManager.GetString("RadioButton_ShowOnlyDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + Down 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + I 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + K 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + L 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + Left 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + O 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + Right 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + Up 的本地化字符串。
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F8 的本地化字符串。
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return ResourceManager.GetString("Shortcut_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F9 的本地化字符串。
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return ResourceManager.GetString("Shortcut_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit External Command 的本地化字符串。
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Commands 的本地化字符串。
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit File Setting 的本地化字符串。
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Settings 的本地化字符串。
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Settings 的本地化字符串。
        /// </summary>
        public static string Title_GeneralSettingWindow {
            get {
                return ResourceManager.GetString("Title_GeneralSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dst File Path 的本地化字符串。
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return ResourceManager.GetString("ToolTip_DstFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dst Sheet 的本地化字符串。
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return ResourceManager.GetString("ToolTip_DstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Src File Path 的本地化字符串。
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return ResourceManager.GetString("ToolTip_SrcFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Src Sheet 的本地化字符串。
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return ResourceManager.GetString("ToolTip_SrcSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap src and dst 的本地化字符串。
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return ResourceManager.GetString("ToolTip_Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Word_Apply {
            get {
                return ResourceManager.GetString("Word_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Args 的本地化字符串。
        /// </summary>
        public static string Word_Args {
            get {
                return ResourceManager.GetString("Word_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blank 的本地化字符串。
        /// </summary>
        public static string Word_Blank {
            get {
                return ResourceManager.GetString("Word_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CaseSensitive 的本地化字符串。
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return ResourceManager.GetString("Word_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Header Index 的本地化字符串。
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return ResourceManager.GetString("Word_ColumnHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Word_Default {
            get {
                return ResourceManager.GetString("Word_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Word_Done {
            get {
                return ResourceManager.GetString("Word_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dst File 的本地化字符串。
        /// </summary>
        public static string Word_DstFile {
            get {
                return ResourceManager.GetString("Word_DstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Word_Edit {
            get {
                return ResourceManager.GetString("Word_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExactMatch 的本地化字符串。
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return ResourceManager.GetString("Word_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable 的本地化字符串。
        /// </summary>
        public static string Word_Executable {
            get {
                return ResourceManager.GetString("Word_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Word_Font {
            get {
                return ResourceManager.GetString("Word_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        public static string Word_Japanese {
            get {
                return ResourceManager.GetString("Word_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launguage 的本地化字符串。
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Type 的本地化字符串。
        /// </summary>
        public static string Word_MatchType {
            get {
                return ResourceManager.GetString("Word_MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Row Header Width 的本地化字符串。
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return ResourceManager.GetString("Word_MaxRowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Word_Path {
            get {
                return ResourceManager.GetString("Word_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex 的本地化字符串。
        /// </summary>
        public static string Word_Regex {
            get {
                return ResourceManager.GetString("Word_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Word_Remove {
            get {
                return ResourceManager.GetString("Word_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Word_Reset {
            get {
                return ResourceManager.GetString("Word_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Header Index 的本地化字符串。
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return ResourceManager.GetString("Word_RowHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Header Name 的本地化字符串。
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return ResourceManager.GetString("Word_RowHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Word_Search {
            get {
                return ResourceManager.GetString("Word_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Word_Setting {
            get {
                return ResourceManager.GetString("Word_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet 的本地化字符串。
        /// </summary>
        public static string Word_Sheet {
            get {
                return ResourceManager.GetString("Word_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet Index 的本地化字符串。
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return ResourceManager.GetString("Word_SheetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet Name 的本地化字符串。
        /// </summary>
        public static string Word_SheetName {
            get {
                return ResourceManager.GetString("Word_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Src File 的本地化字符串。
        /// </summary>
        public static string Word_SrcFile {
            get {
                return ResourceManager.GetString("Word_SrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as Startup Sheet 的本地化字符串。
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return ResourceManager.GetString("Word_StartupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        public static string Word_Tool {
            get {
                return ResourceManager.GetString("Word_Tool", resourceCulture);
            }
        }
    }
}
